/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, TouchableOpacity, View} from 'react-native';
import SVProgressHUD from 'react-native-svprogresshud';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
  };

  onPress2 = async () => {
    console.log(Number(0xffff0000));
    // console.log(255.toString(16));
    const raw = 'rgba(0,0,0,0.5)';
    if (raw.includes('rgba')) {
      const arr = raw.split(',');
      console.log(arr);
    }
    // const color = Color();
    // console.log(color.hex());
  };
  onPress3 = async () => {
    // SVProgressHUD.showInfo();
    // SVProgressHUD.showProgress(0.5, 'Loading...');
    // SVProgressHUD.showProgress(0.5);

    if (Platform.OS == 'android') {
      SVProgressHUD.setBackgroundColor([0, 255, 0, 255]);
      SVProgressHUD.setForegroundColor([255, 255, 255, 255]);
      SVProgressHUD.setDefaultMaskType('black');
      SVProgressHUD.setDefaultStyle('custom');
    } else {
      SVProgressHUD.setDefaultStyle('dark');
      SVProgressHUD.setBackgroundColor([255, 255, 255, 255]);
      SVProgressHUD.setForegroundColor([255, 0, 0, 255]);
      SVProgressHUD.setDefaultMaskType('black');
    }
    // SVProgressHUD.showProgress(0.28, 'Đang xử lý...');
    SVProgressHUD.showError('Có lỗi xảy ra!');
    setTimeout(SVProgressHUD.dismiss, 5000);
  };

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.onPress3}>
          <Text>Show</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  mt: {
    marginBottom: 20,
  },
});
